export const CRUZE_CARS = [
  {
    id: "luxora-zenith",
    name: "Luxora Zenith",
    tagline: "Grand touring coupe",
    category: "business",
    price: 550,
    priceUnit: "day",
    seats: 4,
    gearbox: "Automatic",
    luggage: "3 bags",
    year: 2025,
    engine: "6.5 L V12",
    hp: "759 HP",
    topSpeed: "340 km/h",
    mileage: "10 KM",
    drivetrain: "AWD",
    img: "assets/luxora-zenith.jpg",
    gallery: [
      "assets/hero-car.jpg",
      "assets/velox-horizon.jpg",
      "assets/luxora-zenith.jpg",
      "assets/brand-1.jpg",
      "assets/brand-2.jpg",
    ],
    description: "The Luxora Zenith is the refined expression of modern grand touring. Hand-finished leather, an atelier-spec audio system and a twelve-cylinder drivetrain — made for long, effortless days between cities.",
    features: [
      "LED headlights and taillights",
      "Wireless phone charging",
      "Cruise control",
      "Keyless entry",
      "Heated & ventilated seats",
      "Panoramic glass roof",
      "Bluetooth & Apple CarPlay",
      "Rear A/C vents",
      "22-inch forged wheels",
      "Adaptive cruise, lane-keep assist",
    ],
  },
  {
    id: "velox-horizon",
    name: "Velox Horizon",
    tagline: "Track-bred supercar",
    category: "adventure",
    price: 720,
    priceUnit: "day",
    seats: 2,
    gearbox: "Sequential",
    luggage: "1 bag",
    year: 2025,
    engine: "4.0 L Twin-Turbo V8",
    hp: "820 HP",
    topSpeed: "355 km/h",
    mileage: "5 KM",
    drivetrain: "RWD",
    img: "assets/velox-horizon.jpg",
    gallery: [
      "assets/velox-horizon.jpg",
      "assets/hero-car.jpg",
      "assets/brand-2.jpg",
      "assets/brand-3.jpg",
      "assets/luxora-zenith.jpg",
    ],
    description: "Purpose-built for the ribbon of asphalt that winds up your favourite mountain pass. A carbon monocoque, pushrod-actuated suspension and a naturally-howling V8 engineered with one thing in mind — performance.",
    features: [
      "Carbon fibre monocoque",
      "Pushrod suspension",
      "Ceramic brakes",
      "Launch control",
      "Track telemetry display",
      "Race-harness mounts",
      "Titanium exhaust",
      "Active aero",
    ],
  },
  {
    id: "aurora-strada",
    name: "Aurora Strada",
    tagline: "Daily hybrid supercar",
    category: "business",
    price: 390,
    priceUnit: "day",
    seats: 2,
    gearbox: "Automatic",
    luggage: "2 bags",
    year: 2025,
    engine: "3.0 L Hybrid V6",
    hp: "670 HP",
    topSpeed: "310 km/h",
    mileage: "15 KM",
    drivetrain: "AWD",
    img: "assets/hero-car.jpg",
    gallery: [
      "assets/hero-car.jpg",
      "assets/luxora-zenith.jpg",
      "assets/velox-horizon.jpg",
      "assets/brand-1.jpg",
      "assets/brand-3.jpg",
    ],
    description: "A daily-drivable supercar with a silent EV mode for morning commutes and an on-demand V6 for the weekend. 0–100 in 2.9s — without sacrificing comfort.",
    features: [
      "Hybrid powertrain, 80km EV range",
      "Magnetic ride suspension",
      "Heated steering wheel",
      "Wireless CarPlay",
      "Matrix LED headlights",
      "Head-up display",
      "Surround-view cameras",
      "Adaptive cruise",
    ],
  },
  {
    id: "nocturne-gt",
    name: "Nocturne GT",
    tagline: "Limited-run coupe",
    category: "wedding",
    price: 820,
    priceUnit: "day",
    seats: 2,
    gearbox: "Automatic",
    luggage: "2 bags",
    year: 2024,
    engine: "4.0 L Twin-Turbo V8",
    hp: "720 HP",
    topSpeed: "330 km/h",
    mileage: "12 KM",
    drivetrain: "RWD",
    img: "assets/brand-2.jpg",
    gallery: [
      "assets/brand-2.jpg",
      "assets/velox-horizon.jpg",
      "assets/luxora-zenith.jpg",
      "assets/brand-1.jpg",
      "assets/hero-car.jpg",
    ],
    description: "Only thirty-two were built. A hand-formed aluminum body over a carbon tub, stitched interior in midnight blue, and a drivetrain tuned by the factory's motorsport division. A showpiece for a singular occasion.",
    features: [
      "One-of-32 serial plaque",
      "Hand-formed aluminum body",
      "Bespoke interior colour",
      "Carbon ceramic brakes",
      "Adaptive suspension",
      "Sport exhaust",
      "Premium audio",
      "Nappa leather trim",
    ],
  },
  {
    id: "meridian-s",
    name: "Meridian S",
    tagline: "Electric luxury sedan",
    category: "family",
    price: 310,
    priceUnit: "day",
    seats: 5,
    gearbox: "Automatic",
    luggage: "4 bags",
    year: 2025,
    engine: "Dual electric motors",
    hp: "640 HP",
    topSpeed: "260 km/h",
    mileage: "20 KM",
    drivetrain: "AWD",
    img: "assets/brand-3.jpg",
    gallery: [
      "assets/brand-3.jpg",
      "assets/hero-car.jpg",
      "assets/luxora-zenith.jpg",
      "assets/brand-1.jpg",
      "assets/velox-horizon.jpg",
    ],
    description: "Six-hundred-and-forty miles of range, silent acceleration and a cabin optimised for long family journeys. Four-zone climate, rear captain's chairs, and a 24-speaker sound stage.",
    features: [
      "640 mile EV range",
      "Four-zone climate",
      "Rear captain's chairs",
      "24-speaker audio",
      "Panoramic glass roof",
      "Air suspension",
      "Massaging front seats",
      "Rear entertainment screens",
    ],
  },
  {
    id: "solara-voyage",
    name: "Solara Voyage",
    tagline: "Family grand SUV",
    category: "family",
    price: 220,
    priceUnit: "day",
    seats: 7,
    gearbox: "Automatic",
    luggage: "5 bags",
    year: 2025,
    engine: "3.0 L Turbo I6",
    hp: "490 HP",
    topSpeed: "250 km/h",
    mileage: "18 KM",
    drivetrain: "AWD",
    img: "assets/brand-1.jpg",
    gallery: [
      "assets/brand-1.jpg",
      "assets/luxora-zenith.jpg",
      "assets/hero-car.jpg",
      "assets/brand-3.jpg",
      "assets/velox-horizon.jpg",
    ],
    description: "Seven seats, a refined mild-hybrid straight-six and a quiet cabin worthy of the longest road trip. Practical, powerful, unflappable.",
    features: [
      "Seven-seat configuration",
      "Mild-hybrid powertrain",
      "Air suspension",
      "Heated 2nd row",
      "Panoramic glass roof",
      "Kneeling tailgate",
      "Tow rating 3500kg",
      "Head-up display",
    ],
  },
  {
    id: "royale-phantom",
    name: "Royale Phantom",
    tagline: "Wedding-day limousine",
    category: "wedding",
    price: 950,
    priceUnit: "day",
    seats: 4,
    gearbox: "Automatic",
    luggage: "3 bags",
    year: 2024,
    engine: "6.75 L V12",
    hp: "560 HP",
    topSpeed: "250 km/h",
    mileage: "8 KM",
    drivetrain: "RWD",
    img: "assets/hero-car.jpg",
    gallery: [
      "assets/hero-car.jpg",
      "assets/luxora-zenith.jpg",
      "assets/brand-1.jpg",
      "assets/brand-2.jpg",
      "assets/brand-3.jpg",
    ],
    description: "The Phantom is engineered for arrival. Whisper-quiet at speed, with starlight headliner and coach doors that swing wide for a perfect entrance.",
    features: [
      "Starlight headliner",
      "Coach (suicide) doors",
      "Bespoke two-tone paint",
      "Champagne cooler",
      "Power-assisted doors",
      "Picnic tables rear",
      "Lambswool floormats",
      "Privacy curtains",
    ],
  },
  {
    id: "terra-sierra",
    name: "Terra Sierra",
    tagline: "Overland luxury 4×4",
    category: "adventure",
    price: 280,
    priceUnit: "day",
    seats: 5,
    gearbox: "Automatic",
    luggage: "4 bags",
    year: 2025,
    engine: "4.4 L Twin-Turbo V8",
    hp: "530 HP",
    topSpeed: "230 km/h",
    mileage: "25 KM",
    drivetrain: "4WD",
    img: "assets/brand-3.jpg",
    gallery: [
      "assets/brand-3.jpg",
      "assets/brand-1.jpg",
      "assets/hero-car.jpg",
      "assets/velox-horizon.jpg",
      "assets/luxora-zenith.jpg",
    ],
    description: "An off-road capable SUV that doesn't compromise on the cabin. Locking differentials, raised air suspension and a wading depth to cross just about anything between you and the campsite.",
    features: [
      "Triple locking diffs",
      "Raised air suspension",
      "900mm wading depth",
      "Underbody protection",
      "Off-road cameras",
      "All-terrain tyres",
      "Roof cargo rails",
      "Refrigerated console",
    ],
  },
];
